<a href="https://colab.research.google.com/github/mayurjavare/HPC-DL/blob/main/DL-1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import tensorflow as tf
from tensorflow.keras.datasets import boston_housing
from sklearn import preprocessing

In [16]:
(train_x,train_y),(test_x,test_y) = boston_housing.load_data()

In [17]:
print("train shape :",train_x.shape)
print("Test shape :",test_x.shape)
print("Actual Train Output",train_y.shape)
print("Actual Test Output",test_y.shape)


train shape : (404, 13)
Test shape : (102, 13)
Actual Train Output (404,)
Actual Test Output (102,)


In [18]:
train_x

array([[1.23247e+00, 0.00000e+00, 8.14000e+00, ..., 2.10000e+01,
        3.96900e+02, 1.87200e+01],
       [2.17700e-02, 8.25000e+01, 2.03000e+00, ..., 1.47000e+01,
        3.95380e+02, 3.11000e+00],
       [4.89822e+00, 0.00000e+00, 1.81000e+01, ..., 2.02000e+01,
        3.75520e+02, 3.26000e+00],
       ...,
       [3.46600e-02, 3.50000e+01, 6.06000e+00, ..., 1.69000e+01,
        3.62250e+02, 7.83000e+00],
       [2.14918e+00, 0.00000e+00, 1.95800e+01, ..., 1.47000e+01,
        2.61950e+02, 1.57900e+01],
       [1.43900e-02, 6.00000e+01, 2.93000e+00, ..., 1.56000e+01,
        3.76700e+02, 4.38000e+00]])

In [19]:
train_x[0]

array([  1.23247,   0.     ,   8.14   ,   0.     ,   0.538  ,   6.142  ,
        91.7    ,   3.9769 ,   4.     , 307.     ,  21.     , 396.9    ,
        18.72   ])

In [20]:
test_x[0]

array([ 18.0846,   0.    ,  18.1   ,   0.    ,   0.679 ,   6.434 ,
       100.    ,   1.8347,  24.    , 666.    ,  20.2   ,  27.25  ,
        29.05  ])

In [21]:
train_y[0]

15.2

In [22]:
train_x=preprocessing.normalize(train_x)
test_x=preprocessing.normalize(test_x)

In [23]:
train_x[0]

array([0.0024119 , 0.        , 0.01592969, 0.        , 0.00105285,
       0.01201967, 0.17945359, 0.00778265, 0.00782786, 0.6007879 ,
       0.04109624, 0.77671895, 0.03663436])

In [24]:
train_y[0]

15.2

In [25]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import *
def HousePricePredictionModel():
  model=Sequential()
  model.add(Dense(128,activation='relu',input_shape=(train_x[0].shape)))
  model.add(Dense(64,activation='relu'))
  model.add(Dense(32,activation='relu'))
  model.add(Dense(1))
  model.compile(optimizer='rmsprop',loss='mse',metrics=['mae'])
  return model


In [26]:
import numpy as np
k=4
num_val_samples= len(train_x)
num_epochs = 100
all_scores = []

In [27]:
model = HousePricePredictionModel()
history=model.fit(x=train_x,y=train_y,epochs= num_epochs,batch_size=1,verbose=1,validation_data=(test_x,test_y))

Epoch 1/100
404/404 [==============================] - 2s 4ms/step - loss: 133.4988 - mae: 8.3471 - val_loss: 80.8870 - val_mae: 6.4123
Epoch 2/100
404/404 [==============================] - 2s 4ms/step - loss: 67.9352 - mae: 5.7426 - val_loss: 59.1340 - val_mae: 5.6045
Epoch 3/100
404/404 [==============================] - 2s 4ms/step - loss: 62.8479 - mae: 5.5316 - val_loss: 56.1758 - val_mae: 5.5017
Epoch 4/100
404/404 [==============================] - 1s 3ms/step - loss: 61.4188 - mae: 5.4087 - val_loss: 54.6430 - val_mae: 5.4198
Epoch 5/100
404/404 [==============================] - 3s 8ms/step - loss: 57.9257 - mae: 5.3203 - val_loss: 57.5925 - val_mae: 5.3890
Epoch 6/100
404/404 [==============================] - 2s 4ms/step - loss: 56.4364 - mae: 5.1343 - val_loss: 57.4443 - val_mae: 5.3304
Epoch 7/100
404/404 [==============================] - 1s 3ms/step - loss: 53.5641 - mae: 4.9746 - val_loss: 53.6726 - val_mae: 5.1664
Epoch 8/100
404/404 [==============================] -

In [29]:
test = [[0.02675675, 0.        , 0.02677953, 0.        , 0.0010046 ,
        0.00951931, 0.14795322, 0.0027145 , 0.03550877, 0.98536841,
        0.02988655, 0.04031725, 0.04298041]]
print("Actual Output: ", train_y[0])
print("Predicted Output: ", model.predict(test))

Actual Output:  15.2
1/1 [==============================] - 0s 48ms/step
Predicted Output:  [[9.479875]]
