<a href="https://colab.research.google.com/github/mayurjavare/HPC-DL/blob/main/Welcome_To_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
from tensorflow.keras.datasets import boston_housing
from sklearn import preprocessing

In [2]:
(train_x,train_y),(test_x,test_y) = boston_housing.load_data()

57026/57026 [==============================] - 0s 0us/step


In [3]:
print("train shape :",train_x.shape)
print("Test shape :",test_x.shape)
print("Actual Train Output",train_y.shape)
print("Actual Test Output",test_y.shape)


train shape : (404, 13)
Test shape : (102, 13)
Actual Train Output (404,)
Actual Test Output (102,)


In [4]:
train_x

array([[1.23247e+00, 0.00000e+00, 8.14000e+00, ..., 2.10000e+01,
        3.96900e+02, 1.87200e+01],
       [2.17700e-02, 8.25000e+01, 2.03000e+00, ..., 1.47000e+01,
        3.95380e+02, 3.11000e+00],
       [4.89822e+00, 0.00000e+00, 1.81000e+01, ..., 2.02000e+01,
        3.75520e+02, 3.26000e+00],
       ...,
       [3.46600e-02, 3.50000e+01, 6.06000e+00, ..., 1.69000e+01,
        3.62250e+02, 7.83000e+00],
       [2.14918e+00, 0.00000e+00, 1.95800e+01, ..., 1.47000e+01,
        2.61950e+02, 1.57900e+01],
       [1.43900e-02, 6.00000e+01, 2.93000e+00, ..., 1.56000e+01,
        3.76700e+02, 4.38000e+00]])

In [5]:
train_x[0]

array([  1.23247,   0.     ,   8.14   ,   0.     ,   0.538  ,   6.142  ,
        91.7    ,   3.9769 ,   4.     , 307.     ,  21.     , 396.9    ,
        18.72   ])

In [6]:
test_x[0]

array([ 18.0846,   0.    ,  18.1   ,   0.    ,   0.679 ,   6.434 ,
       100.    ,   1.8347,  24.    , 666.    ,  20.2   ,  27.25  ,
        29.05  ])

In [7]:
train_y[0]

15.2

In [8]:
train_x=preprocessing.normalize(train_x)
test_x=preprocessing.normalize(test_x)

In [9]:
train_x[0]

array([0.0024119 , 0.        , 0.01592969, 0.        , 0.00105285,
       0.01201967, 0.17945359, 0.00778265, 0.00782786, 0.6007879 ,
       0.04109624, 0.77671895, 0.03663436])

In [10]:
train_y[0]

15.2

In [11]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import *
def HousePricePredictionModel():
  model=Sequential()
  model.add(Dense(128,activation='relu',input_shape=(train_x[0].shape)))
  model.add(Dense(64,activation='relu'))
  model.add(Dense(32,activation='relu'))
  model.add(Dense(1))
  model.compile(optimizer='rmsprop',loss='mse',metrics=['mae'])
  return model


In [12]:
import numpy as np
k=4
num_val_samples= len(train_x)
num_epochs = 100
all_scores = []

In [13]:
model = HousePricePredictionModel()
history=model.fit(x=train_x,y=train_y,epochs= num_epochs,batch_size=1,verbose=1,validation_data=(test_x,test_y))

Epoch 1/100
404/404 [==============================] - 2s 3ms/step - loss: 121.3319 - mae: 8.0122 - val_loss: 67.6973 - val_mae: 6.0330
Epoch 2/100
404/404 [==============================] - 1s 3ms/step - loss: 68.1088 - mae: 5.8137 - val_loss: 58.4443 - val_mae: 5.6490
Epoch 3/100
404/404 [==============================] - 1s 3ms/step - loss: 62.8875 - mae: 5.5251 - val_loss: 64.1468 - val_mae: 5.7026
Epoch 4/100
404/404 [==============================] - 1s 2ms/step - loss: 61.1859 - mae: 5.4123 - val_loss: 54.5062 - val_mae: 5.5611
Epoch 5/100
404/404 [==============================] - 1s 2ms/step - loss: 58.9509 - mae: 5.2650 - val_loss: 54.1487 - val_mae: 5.3460
Epoch 6/100
404/404 [==============================] - 1s 2ms/step - loss: 55.9844 - mae: 5.2321 - val_loss: 70.9070 - val_mae: 5.9279
Epoch 7/100
404/404 [==============================] - 1s 2ms/step - loss: 54.7506 - mae: 4.9468 - val_loss: 53.6732 - val_mae: 5.5677
Epoch 8/100
404/404 [==============================] -

In [14]:
test = [[0.02675675, 0.        , 0.02677953, 0.        , 0.0010046 ,
        0.00951931, 0.14795322, 0.0027145 , 0.03550877, 0.98536841,
        0.02988655, 0.04031725, 0.04298041]]
print("Actual Output: ", train_y[0])
print("Predicted Output: ", model.predict(test))

Actual Output:  15.2
1/1 [==============================] - 0s 222ms/step
Predicted Output:  [[10.647051]]
